-- CONFI CONSULTORIA | CONTROLE FISCAL INTERNO
create extension if not exists pgcrypto;
create type public.app_role as enum ('ADMINISTRADOR','ANALISTA','CONSULTA');
create type public.tax_sphere as enum ('MUNICIPAL','ESTADUAL','FEDERAL');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,nome text not null,email text not null,perfil public.app_role not null default 'CONSULTA',ativo boolean not null default true,ultimo_acesso timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.companies(id uuid primary key default gen_random_uuid(),codigo text unique not null,razao_social text not null,nome_curto text,cnpj text,tipo_unidade text,cnpj_matriz text,municipio text,uf char(2),regime text,cnae_principal text,cnaes_secundarios text,status text,responsavel_id uuid references public.profiles(id),inscricao_municipal text,inscricao_estadual text,obrigacao_municipal boolean,obrigacao_estadual boolean,obrigacao_federal boolean,certificado_status text,vencimento_certificado date,procuracao_status text,vencimento_procuracao date,portal_municipal text,portal_estadual text,portal_federal text,observacoes text,ativo boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.competencies(id uuid primary key default gen_random_uuid(),competencia char(6) unique not null check(competencia ~ '^[0-9]{6}$'),ano integer not null,mes integer not null check(mes between 1 and 12),status text not null,responsavel_id uuid references public.profiles(id),data_abertura date,data_fechamento date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.routines(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,competency_id uuid not null references public.competencies(id) on delete cascade,esfera public.tax_sphere not null,categoria text,tipo_demanda text,obrigacao text not null,descricao text,prioridade text,status text not null,data_limite date,responsavel_id uuid references public.profiles(id),impacto text,risco text,pendencia_resumo text,observacao text,proximo_passo text,status_externo text,ultima_movimentacao timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.guides(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,competency_id uuid not null references public.competencies(id) on delete cascade,routine_id uuid references public.routines(id) on delete set null,esfera public.tax_sphere not null,tributo text,tipo_guia text,valor numeric(14,2) not null default 0 check(valor>=0),vencimento date,emitida boolean default false,data_emissao date,enviada boolean default false,data_envio date,cliente_confirmou boolean default false,paga boolean default false,data_pagamento date,comprovante_recebido boolean default false,data_comprovante date,responsavel_id uuid references public.profiles(id),observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.issues(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,competency_id uuid not null references public.competencies(id) on delete cascade,routine_id uuid references public.routines(id) on delete set null,guide_id uuid references public.guides(id) on delete set null,esfera public.tax_sphere,origem text,tipo text,descricao text not null,status text not null,prioridade text,responsavel_id uuid references public.profiles(id),prazo date,risco text,acao_recomendada text,observacao text,solucao text,data_abertura timestamptz default now(),data_encerramento timestamptz,automatica boolean default false,chave_origem text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index issues_auto_unique on public.issues(company_id,competency_id,chave_origem) where automatica=true and data_encerramento is null;
create table public.transfers(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id) on delete cascade,competency_id uuid not null references public.competencies(id) on delete cascade,decisao text,risco_geral text,setor_prioritario text,entregue boolean default false,data_entrega timestamptz,responsavel_id uuid references public.profiles(id),recebido_por text,data_recebimento timestamptz,protocolo text,observacao text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,competency_id));
create table public.user_company_access(user_id uuid references public.profiles(id) on delete cascade,company_id uuid references public.companies(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,company_id));
create table public.audit_logs(id bigint generated always as identity primary key,user_id uuid,acao text not null,tabela text not null,registro_id uuid,company_id uuid,competency_id uuid,valor_anterior jsonb,valor_novo jsonb,origem text default 'APP',observacao text,created_at timestamptz not null default now());
create table public.system_settings(id uuid primary key default gen_random_uuid(),chave text unique not null,valor jsonb not null default '{}'::jsonb,updated_at timestamptz default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,titulo text not null,mensagem text,lida boolean default false,created_at timestamptz default now());

create index routines_company_comp_sphere on public.routines(company_id,competency_id,esfera);create index routines_due on public.routines(data_limite);create index guides_company_comp on public.guides(company_id,competency_id);create index issues_company_comp on public.issues(company_id,competency_id);

create or replace function public.current_user_role() returns public.app_role language sql stable security definer set search_path=public as $$ select perfil from public.profiles where id=auth.uid() and ativo=true $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_user_role()='ADMINISTRADOR',false) $$;
create or replace function public.can_access_company(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_admin() or exists(select 1 from public.user_company_access where user_id=auth.uid() and company_id=cid) $$;

alter table public.profiles enable row level security;alter table public.companies enable row level security;alter table public.competencies enable row level security;alter table public.routines enable row level security;alter table public.guides enable row level security;alter table public.issues enable row level security;alter table public.transfers enable row level security;alter table public.user_company_access enable row level security;alter table public.audit_logs enable row level security;alter table public.system_settings enable row level security;alter table public.notifications enable row level security;

create policy profiles_self_or_admin_select on public.profiles for select using(id=auth.uid() or public.is_admin());
create policy profiles_admin_write on public.profiles for all using(public.is_admin()) with check(public.is_admin());
create policy companies_select on public.companies for select using(public.can_access_company(id));
create policy companies_admin_write on public.companies for all using(public.is_admin()) with check(public.is_admin());
create policy competencies_authenticated_select on public.competencies for select using(auth.uid() is not null);
create policy competencies_admin_write on public.competencies for all using(public.is_admin()) with check(public.is_admin());
create policy routines_select on public.routines for select using(public.can_access_company(company_id));
create policy routines_analyst_write on public.routines for insert with check(public.current_user_role() in ('ADMINISTRADOR','ANALISTA') and public.can_access_company(company_id));
create policy routines_update on public.routines for update using(public.current_user_role() in ('ADMINISTRADOR','ANALISTA') and public.can_access_company(company_id)) with check(public.can_access_company(company_id));
create policy guides_select on public.guides for select using(public.can_access_company(company_id));
create policy guides_write on public.guides for all using(public.current_user_role() in ('ADMINISTRADOR','ANALISTA') and public.can_access_company(company_id)) with check(public.can_access_company(company_id));
create policy issues_select on public.issues for select using(public.can_access_company(company_id));
create policy issues_write on public.issues for all using(public.current_user_role() in ('ADMINISTRADOR','ANALISTA') and public.can_access_company(company_id)) with check(public.can_access_company(company_id));
create policy transfers_select on public.transfers for select using(public.can_access_company(company_id));
create policy transfers_write on public.transfers for all using(public.current_user_role() in ('ADMINISTRADOR','ANALISTA') and public.can_access_company(company_id)) with check(public.can_access_company(company_id));
create policy access_admin on public.user_company_access for all using(public.is_admin()) with check(public.is_admin());
create policy audit_select_admin on public.audit_logs for select using(public.is_admin());
create policy settings_select on public.system_settings for select using(auth.uid() is not null);create policy settings_admin on public.system_settings for all using(public.is_admin()) with check(public.is_admin());
create policy notifications_own on public.notifications for select using(user_id=auth.uid());

create or replace function public.audit_row() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.audit_logs(user_id,acao,tabela,registro_id,valor_anterior,valor_novo) values(auth.uid(),tg_op,tg_table_name,coalesce(new.id,old.id),case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end);return coalesce(new,old);end $$;
create trigger audit_companies after insert or update or delete on public.companies for each row execute function public.audit_row();
create trigger audit_routines after insert or update or delete on public.routines for each row execute function public.audit_row();
create trigger audit_guides after insert or update or delete on public.guides for each row execute function public.audit_row();
create trigger audit_issues after insert or update or delete on public.issues for each row execute function public.audit_row();
create trigger audit_transfers after insert or update or delete on public.transfers for each row execute function public.audit_row();
